/*
    ClockNWorkEvent.cpp

    
MIT License

Copyright (c) 2016 cbtek

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

*/
//----------------------------------------
//ClockNWorkEvent.cpp generated by cbtek on 11-13-2016 at 02:58:43 PM
//----------------------------------------
#include "ClockNWorkEvent.h"

namespace cbtek {
namespace products {
namespace productivity {
namespace clock_n_work {


ClockNWorkEvent::ClockNWorkEvent()
{
    m_eventType = EventType::NONE;
}

ClockNWorkEvent::~ClockNWorkEvent()
{

}

void ClockNWorkEvent::setId(const std::string & value)
{
    m_id=value;
}

void ClockNWorkEvent::setEventType(const EventType & value)
{
    m_eventType = value;
}

void ClockNWorkEvent::setComment(const std::string & value)
{
    m_comment = value;
}

void ClockNWorkEvent::setStartTime(std::uint64_t value)
{
    m_startTime=value;
}

void ClockNWorkEvent::setEndTime(std::uint64_t value)
{
    m_endTime=value;
}


std::string ClockNWorkEvent::getId() const
{
    return m_id;
}

const EventType &ClockNWorkEvent::getEventType() const
{
    return m_eventType;
}

std::string ClockNWorkEvent::getComment() const
{
    return m_comment;
}

std::uint64_t ClockNWorkEvent::getStartTime() const
{
    return m_startTime;
}

std::uint64_t ClockNWorkEvent::getEndTime() const
{
    return m_endTime;
}


}}}}//end namespace


